#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prepare_origin_data.py

Convert raw MATLAB-style Excel data into the standardized Origin workbook
consumed by the plotting backends.

Specification JSON schema (one panel):
{
  "layout": "three_panel",
  "figure_name": "Fig2",
  "source": "../data/Fig2_raw.xlsx",
  "sheet": "Data",
  "output_excel": "../generated/Fig2_origin.xlsx",
  "condition": "generated by MATLAB",
  "panels": {
    "a": {
      "x_row": 1,
      "y_rows": [2, 4, 6],
      "N_in": [0.5, 0.7, 1.0],
      "x_variable": "delta",
      "y_variable": "GdB"
    }
  }
}

Rows are 1-based row numbers in the source sheet. The generated workbook
contains one sheet per panel:

  single      -> <figure_name>_Standard
  two_panel   -> FigA, FigB
  three_panel -> FigA, FigB, FigC
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

import numpy as np
import pandas as pd
from openpyxl import Workbook


SUPPORTED_LAYOUTS = ("single", "two_panel", "three_panel")
PANEL_SHEET_NAMES = {"a": "FigA", "b": "FigB", "c": "FigC"}


def resolve_path(value: str, base_dir: Path) -> Path:
    path = Path(value).expanduser()
    return path if path.is_absolute() else (base_dir / path).resolve()


def load_spec(spec_path: Path) -> Dict[str, Any]:
    try:
        raw = json.loads(spec_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        raise SystemExit(f"Spec file not found: {spec_path}")
    except json.JSONDecodeError as e:
        raise SystemExit(f"Invalid JSON in {spec_path}: {e}")
    if not isinstance(raw, dict):
        raise SystemExit(f"Spec must be a JSON object: {spec_path}")
    return raw


def numeric_row(row: Iterable[Any]) -> np.ndarray:
    values = pd.to_numeric(pd.Series(list(row)), errors="coerce")
    return values.to_numpy(dtype=float)


def load_source_rows(source: Path, sheet_name: str) -> pd.DataFrame:
    try:
        xls = pd.ExcelFile(source)
    except Exception as e:
        raise SystemExit(f"Could not open source workbook '{source}': {e}")

    available = list(xls.sheet_names)
    if not sheet_name:
        if len(available) == 1:
            sheet_name = available[0]
        else:
            raise SystemExit(
                f"Spec must name a source sheet. Available sheets: {', '.join(available)}"
            )
    if sheet_name not in available:
        raise SystemExit(
            f"Sheet '{sheet_name}' not found in '{source.name}'. "
            f"Available sheets: {', '.join(available)}"
        )
    try:
        return pd.read_excel(xls, sheet_name=sheet_name, header=None)
    except Exception as e:
        raise SystemExit(f"Could not read sheet '{sheet_name}' from '{source.name}': {e}")


def extract_curve_from_rows(
    source_df: pd.DataFrame,
    panel: Dict[str, Any],
    curve_index: int,
) -> Tuple[int, np.ndarray, np.ndarray, float, str, str, str]:
    """Extract one curve from row-oriented raw data."""
    x_row = int(panel["x_row"])
    y_rows = [int(r) for r in panel["y_rows"]]
    n_in_values = [float(v) for v in panel.get("N_in", [])]

    if len(y_rows) != len(n_in_values):
        raise SystemExit(
            f"Panel has {len(y_rows)} y_rows but {len(n_in_values)} N_in values; "
            "they must match."
        )

    if x_row < 1 or x_row > len(source_df):
        raise SystemExit(
            f"x_row {x_row} is outside the source sheet (rows 1..{len(source_df)})."
        )

    y_row = y_rows[curve_index]
    if y_row < 1 or y_row > len(source_df):
        raise SystemExit(
            f"y_row {y_row} for curve {curve_index + 1} is outside the source "
            f"sheet (rows 1..{len(source_df)})."
        )

    x = numeric_row(source_df.iloc[x_row - 1, :])
    y = numeric_row(source_df.iloc[y_row - 1, :])
    if len(x) != len(y):
        raise SystemExit("Source sheet has ragged rows; each row must have the same width.")

    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    if len(x) == 0:
        raise SystemExit(
            f"Rows {x_row}/{y_row} contain no numeric X/Y pairs. "
            "Check the requested rows or source data."
        )

    n_in = n_in_values[curve_index]
    x_variable = str(panel.get("x_variable") or "x")
    y_variable = str(panel.get("y_variable") or "y")
    condition = str(panel.get("condition") or "")
    return y_row, x, y, n_in, x_variable, y_variable, condition


def extract_curve_from_columns(
    source_df: pd.DataFrame,
    panel: Dict[str, Any],
    curve_index: int,
) -> Tuple[int, np.ndarray, np.ndarray, float, str, str, str]:
    """Extract one curve from column-oriented raw data."""
    x_column = int(panel["x_column"])
    y_columns = [int(c) for c in panel["y_columns"]]
    n_in_values = [float(v) for v in panel.get("N_in", [])]

    if len(y_columns) != len(n_in_values):
        raise SystemExit(
            f"Panel has {len(y_columns)} y_columns but {len(n_in_values)} N_in values; "
            "they must match."
        )

    ncols = source_df.shape[1]
    if x_column < 1 or x_column > ncols:
        raise SystemExit(
            f"x_column {x_column} is outside the source sheet (columns 1..{ncols})."
        )

    y_column = y_columns[curve_index]
    if y_column < 1 or y_column > ncols:
        raise SystemExit(
            f"y_column {y_column} for curve {curve_index + 1} is outside the source "
            f"sheet (columns 1..{ncols})."
        )

    x = numeric_row(source_df.iloc[:, x_column - 1])
    y = numeric_row(source_df.iloc[:, y_column - 1])
    mask = np.isfinite(x) & np.isfinite(y)
    x = x[mask]
    y = y[mask]
    if len(x) == 0:
        raise SystemExit(
            f"Columns {x_column}/{y_column} contain no numeric X/Y pairs. "
            "Check the requested columns or source data."
        )

    n_in = n_in_values[curve_index]
    x_variable = str(panel.get("x_variable") or "x")
    y_variable = str(panel.get("y_variable") or "y")
    condition = str(panel.get("condition") or "")
    return y_column, x, y, n_in, x_variable, y_variable, condition


def extract_curve(
    source_df: pd.DataFrame,
    panel: Dict[str, Any],
    curve_index: int,
) -> Tuple[int, np.ndarray, np.ndarray, float, str, str, str]:
    """Return (selector, x, y, n_in, x_variable, y_variable, condition)."""
    if "y_columns" in panel:
        return extract_curve_from_columns(source_df, panel, curve_index)
    return extract_curve_from_rows(source_df, panel, curve_index)


def panel_sheet_name(layout: str, panel_key: str, figure_name: str) -> str:
    if layout == "single":
        return f"{figure_name}_Standard"
    return PANEL_SHEET_NAMES.get(str(panel_key).lower(), f"Fig{panel_key}")


def write_standardized_workbook(
    output_excel: Path,
    layout: str,
    figure_name: str,
    panels: Dict[str, List[Dict[str, Any]]],
    global_condition: str,
    parameter_name: str = "N_in",
) -> None:
    output_excel.parent.mkdir(parents=True, exist_ok=True)
    wb = Workbook()
    wb.remove(wb.active)

    for panel_key, curves in panels.items():
        sheet_name = panel_sheet_name(layout, panel_key, figure_name)
        ws = wb.create_sheet(sheet_name)
        ws.cell(row=7, column=1, value=f"parameter_name={parameter_name}")

        for i, curve in enumerate(curves, start=1):
            curve_id = i
            n_in = curve["n_in"]
            x_var = curve["x_variable"]
            y_var = curve["y_variable"]
            condition = curve["condition"] or global_condition
            col = (i - 1) * 2

            ws.cell(row=1, column=col + 1, value=f"x_{i}")
            ws.cell(row=1, column=col + 2, value=f"y_{i}")
            ws.cell(row=2, column=col + 1, value="X")
            ws.cell(row=2, column=col + 2, value="Y")
            ws.cell(row=3, column=col + 1, value=curve_id)
            ws.cell(row=3, column=col + 2, value=curve_id)
            ws.cell(row=4, column=col + 1, value=n_in)
            ws.cell(row=4, column=col + 2, value=n_in)
            ws.cell(row=5, column=col + 1, value=x_var)
            ws.cell(row=5, column=col + 2, value=y_var)
            ws.cell(row=6, column=col + 1, value=condition)
            ws.cell(row=6, column=col + 2, value=condition)

            x, y = curve["x"], curve["y"]
            for offset, value in enumerate(x):
                ws.cell(row=8 + offset, column=col + 1, value=float(value))
            for offset, value in enumerate(y):
                ws.cell(row=8 + offset, column=col + 2, value=float(value))

    wb.save(output_excel)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Convert raw MATLAB-style Excel data to the standardized Origin format."
    )
    parser.add_argument("--spec", required=True, help="Path to the plot specification JSON.")
    parser.add_argument(
        "--output-excel", default=None, help="Optional override for the output workbook path."
    )
    args = parser.parse_args()

    spec_path = Path(args.spec).resolve()
    spec = load_spec(spec_path)
    spec_dir = spec_path.parent

    layout = str(spec.get("layout", "")).strip().lower()
    figure_name = str(spec.get("figure_name", "")).strip()
    if not figure_name:
        raise SystemExit("Spec must include a non-empty figure_name.")

    panels_raw = spec.get("panels")
    if not isinstance(panels_raw, dict) or not panels_raw:
        raise SystemExit("Spec must include a non-empty 'panels' object.")

    panel_keys = list(panels_raw.keys())
    if not layout:
        layout = {1: "single", 2: "two_panel", 3: "three_panel"}.get(len(panel_keys))
    if layout not in SUPPORTED_LAYOUTS:
        raise SystemExit(
            f"Unsupported layout '{layout}'. Expected one of: {', '.join(SUPPORTED_LAYOUTS)}."
        )
    if layout != "single" and len(panel_keys) not in (2, 3):
        raise SystemExit(f"Layout '{layout}' requires 2 or 3 panels, got {len(panel_keys)}.")
    if layout == "single" and len(panel_keys) != 1:
        raise SystemExit("Layout 'single' requires exactly 1 panel.")

    source = resolve_path(str(spec.get("source", "")), spec_dir)
    if not source.exists():
        raise SystemExit(f"Source file not found: {source}")
    sheet_name = str(spec.get("sheet") or "")
    source_df = load_source_rows(source, sheet_name)

    output_excel = resolve_path(
        str(spec.get("output_excel") or f"../generated/{figure_name}_origin.xlsx"),
        spec_dir,
    )
    if args.output_excel:
        output_excel = Path(args.output_excel).resolve()

    global_condition = str(spec.get("condition") or "")
    parameter_name = str(spec.get("parameter_name") or "N_in")
    panels: Dict[str, List[Dict[str, Any]]] = {}
    for panel_key in panel_keys:
        panel = panels_raw[panel_key]
        if not isinstance(panel, dict):
            raise SystemExit(f"Panel '{panel_key}' must be an object.")
        has_rows = "x_row" in panel and "y_rows" in panel
        has_columns = "x_column" in panel and "y_columns" in panel
        if not (has_rows or has_columns):
            raise SystemExit(
                f"Panel '{panel_key}' must include either x_row/y_rows or "
                "x_column/y_columns."
            )

        curve_count = len(panel["y_rows"]) if has_rows else len(panel["y_columns"])
        curves = []
        for index in range(curve_count):
            _, x, y, n_in, x_var, y_var, condition = extract_curve(
                source_df, panel, index
            )
            curves.append(
                {
                    "x": x,
                    "y": y,
                    "n_in": n_in,
                    "x_variable": x_var,
                    "y_variable": y_var,
                    "condition": condition,
                }
            )
        panels[str(panel_key)] = curves

    write_standardized_workbook(
        output_excel, layout, figure_name, panels, global_condition, parameter_name
    )

    summary = {
        "figure": figure_name,
        "layout": layout,
        "source": str(source),
        "output_excel": str(output_excel),
        "panels": {
            key: {
                "sheet": panel_sheet_name(layout, key, figure_name),
                "series": [
                    {
                        "curve_id": i + 1,
                        "N_in": c["n_in"],
                        "n_points": int(len(c["x"])),
                    }
                    for i, c in enumerate(curves)
                ],
            }
            for key, curves in panels.items()
        },
    }
    print(json.dumps(summary, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
